/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ozu.mapp.agent.client.ui;

import edu.ozu.mapp.agent.client.AgentHandler;
import edu.ozu.mapp.agent.client.handlers.World;

import javax.swing.*;

/**
 *
 * @author freedrone
 */
public class WorldsPanel extends javax.swing.JPanel {
    private String world_id = "";
    private AgentUI parent;
    private AgentHandler client;

    /**
     * Creates new form WorldsPanel
     */
    public WorldsPanel() {
        initComponents();
        onComponentsDidMount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        join_confirm = new javax.swing.JDialog();
        javax.swing.JPanel join_confirm_container = new javax.swing.JPanel();
        join_confirm_text = new javax.swing.JLabel();
        javax.swing.JButton join_confirm_btn = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        worlds_list = new javax.swing.JList<>();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JButton refresh_btn = new javax.swing.JButton();
        join_btn = new javax.swing.JButton();

        join_confirm.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        join_confirm.setAlwaysOnTop(true);
        join_confirm.setResizable(false);
        join_confirm.setSize(new java.awt.Dimension(300, 150));
        join_confirm.getContentPane().setLayout(new java.awt.FlowLayout());

        join_confirm_container.setPreferredSize(new java.awt.Dimension(240, 100));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 35, 0, 35, 0};
        jPanel3Layout.rowHeights = new int[] {0, 15, 0};
        join_confirm_container.setLayout(jPanel3Layout);

        join_confirm_text.setText("Joining");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        join_confirm_container.add(join_confirm_text, gridBagConstraints);

        join_confirm_btn.setText("OK");
        join_confirm_btn.setMaximumSize(new java.awt.Dimension(100, 50));
        join_confirm_btn.setPreferredSize(new java.awt.Dimension(100, 35));
        join_confirm_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                join_confirm_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        join_confirm_container.add(join_confirm_btn, gridBagConstraints);

        join_confirm.getContentPane().add(join_confirm_container);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(1, 0, 0);
        flowLayout1.setAlignOnBaseline(true);
        setLayout(flowLayout1);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 220));

        worlds_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "No servers found" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        worlds_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        worlds_list.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        worlds_list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                worlds_listValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(worlds_list);

        add(jScrollPane1);

        jPanel1.setMinimumSize(new java.awt.Dimension(79, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 40));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 30, 0};
        jPanel1Layout.rowHeights = new int[] {0};
        jPanel1.setLayout(jPanel1Layout);

        refresh_btn.setText("REFRESH");
        refresh_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refresh_btn.setPreferredSize(new java.awt.Dimension(100, 31));
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(refresh_btn, gridBagConstraints);

        join_btn.setText("JOIN");
        join_btn.setPreferredSize(new java.awt.Dimension(100, 31));
        join_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                join_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel1.add(join_btn, gridBagConstraints);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    void setParent(AgentUI ui) { this.parent = ui; }

    void setClientRef(AgentHandler client) { this.client = client; }

    private void join_btnActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_join_btnActionPerformed
        if (!world_id.isEmpty())
        {
            join();
        }
    }//GEN-LAST:event_join_btnActionPerformed

    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_refresh_btnActionPerformed
        getWorldList();
    }//GEN-LAST:event_refresh_btnActionPerformed

    private void worlds_listValueChanged(javax.swing.event.ListSelectionEvent event)
    {//GEN-FIRST:event_worlds_listValueChanged
        if (!event.getValueIsAdjusting())
        {
            ListSelectionModel lsm = ((javax.swing.JList) event.getSource()).getSelectionModel();
            if (lsm.isSelectionEmpty())
            {
                world_id = "";
                join_btn.setEnabled(false);
            } else {
                world_id = worlds_list.getSelectedValue();
                join_btn.setEnabled(true);
            }
        }
    }//GEN-LAST:event_worlds_listValueChanged

    private void join_confirm_btnActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_join_confirm_btnActionPerformed
        join_confirm.setVisible(false);
        parent.join(world_id);
        join_confirm.dispose();
    }//GEN-LAST:event_join_confirm_btnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton join_btn;
    private javax.swing.JDialog join_confirm;
    private javax.swing.JLabel join_confirm_text;
    private javax.swing.JList<String> worlds_list;
    // End of variables declaration//GEN-END:variables

    private void onComponentsDidMount()
    {
        if (world_id.isEmpty())
        {
            join_btn.setEnabled(false);
        }
    }

    private void getWorldList()
    {// fetch worlds list
        worlds_list.setListData(World.list());
    }

    private void join()
    {
        join_confirm.setVisible(true);
        join_confirm.setTitle(client.getAgentName());
        join_confirm_text.setText("Joining to \n<" + world_id + ">");
    }

    void loadList() { getWorldList(); }
}
