/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ozu.mapp.agent.client.world;

/**
 *
 * @author freedrone
 */
public class WorldHistoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form WorldHistoryPanel
     */
    public WorldHistoryPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dropdown = new javax.swing.JComboBox<>();
        canvas = new java.awt.Canvas();

        setLayout(new java.awt.BorderLayout());

        add(dropdown, java.awt.BorderLayout.NORTH);
        add(canvas, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas;
    private javax.swing.JComboBox<String> dropdown;
    // End of variables declaration//GEN-END:variables
}
