/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ozu.mapp.agent.client.world;

import edu.ozu.mapp.dataTypes.WorldSnapshot;
import edu.ozu.mapp.system.Colors;
import edu.ozu.mapp.utils.Path;
import edu.ozu.mapp.utils.Point;

import java.awt.*;
import java.util.Arrays;
import java.util.HashMap;

/**
 *
 * @author freedrone
 */
public class WorldHistoryCanvas extends javax.swing.JPanel {

    /**
     * Creates new form WorldHistoryCanvas
     */
    public WorldHistoryCanvas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public WorldSnapshot snapshot = null;
    public String[] agent_keys = null;

    private HashMap<String, String> agent_colors = new HashMap<>();
    private int offset  = 1;

    @SuppressWarnings("DuplicatedCode")
    @Override
    public void paint(Graphics graphics)
    {
        super.paint(graphics);

        if (snapshot == null) return;

        // PREPROCESS
        Graphics2D g = (Graphics2D) graphics.create();

        int width   = snapshot.world_width;
        int height  = snapshot.world_height;

        int cell_size = calculate_cell_size(width, height);

        // DRAW CELL BORDERS
        for (int i = 0; i <= width; i++)
        {
            g.setColor(Color.BLACK);
            g.drawLine((offset + i * cell_size), offset, (offset + i * cell_size), (offset + cell_size * height));
            g.drawLine(offset, (offset + i * cell_size), (offset + cell_size * width), (offset + i * cell_size));
        }

        for (String agent_key: agent_keys)
        {
            Point loc = snapshot.locations.get(agent_key);

            Color color = Colors.hex2rgb(agent_colors.get(agent_key));
            if (color == null) {
                color = Colors.hex2rgb(get_color(agent_key));
            }

            g.setColor(color);
            g.setStroke(new BasicStroke());

            Path path = new Path(snapshot.paths.get(agent_key));
            boolean is_planned = false;
            for (int i = 0; i < path.size(); i++)
            {
                Point curr = path.get(i);

                if (curr.equals(loc))
                {
                    // will be drawing planned path from now on
                    is_planned = true;

                    // DRAW AGENT CURRENT LOCATION
                    g.fillOval((curr.x * cell_size), (curr.y * cell_size), cell_size, cell_size);

                    // DRAW AGENT CURRENT LOCATION IDENTIFIER
                    g.setColor(Color.RED);
                    g.drawString(agent_key.split("_")[1], ((curr.x * cell_size) + 2), ((curr.y * cell_size) + 13));

                    g.setColor(color);
                }

                if (i + 1 >= path.size())
                {
                    // DRAW AGENT TARGET LOCATION
                    g.fillRect(
                        (offset + (curr.x * cell_size) + (int) (cell_size * 0.25)),
                        (offset + (curr.y * cell_size) + (int) (cell_size * 0.25)),
                        (int) (cell_size * 0.5),
                        (int) (cell_size * 0.5)
                    );
                    continue;
                }

                // DRAW AGENT PATH
                if (is_planned)
                {
                    Stroke dashed = new BasicStroke(1, BasicStroke.CAP_BUTT, BasicStroke.JOIN_ROUND, 1, new float[]{2f, 0f, 2f}, 2f);
                    g.setStroke(dashed);
                }

                Point next = path.get(i + 1);
                g.drawLine(
                    ((curr.x * cell_size) + (cell_size / 2)), ((curr.y * cell_size) + (cell_size / 2)),
                    ((next.x * cell_size) + (cell_size / 2)), ((next.y * cell_size) + (cell_size / 2))
                );
            }
        }
    }

    private String get_color(String agent_key)
    {
        String hex = Colors.get(agent_colors.keySet().size());
        agent_colors.put(agent_key, hex);

        return hex;
    }

    private final HashMap<String, Integer> cell_size_mem = new HashMap<>();
    private int calculate_cell_size(int width, int height)
    {
        int canvas_height = this.getHeight()- 3;
        int canvas_width  = this.getWidth() - 3;

        Integer cell_size = cell_size_mem.get(String.format("%s-%s", canvas_width, canvas_height));
        if (cell_size == null)
        {
            int shortest_corner = Math.min(canvas_height, canvas_width);
            int divider = Math.max(width, height);

            cell_size = shortest_corner / divider;

            cell_size_mem.put(String.format("%s-%s", canvas_width, canvas_height), cell_size);
        }

        return cell_size;
    }
}
